---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-fibonacci
  labels:
    app: node-fibonacci
spec:
  replicas: 10
  selector:
    matchLabels:
      app: node-fibonacci
  template:
    metadata:
      labels:
        app: node-fibonacci
    spec:
      containers:
      - name: node-fibonacci
        image: docker451001/node-fibonacci:1.0
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: node-fibonacci
spec:
  selector:
    app: node-fibonacci
  ports:
  - name: example-port
    protocol: TCP
    port: 3000
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-fibonacci
spec:
  maxReplicas: 10
  minReplicas: 7
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-fibonacci
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 100Mi
